language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t puneetsinghania2002/react-test -f ./client/Dockerfile.dev ./client
  
script:
    - docker run -e CI=true puneetsinghania2002/react-test npm test 
  
after_success:
  - docker build -t puneetsinghania2002/multi-client ./client
  - docker build -t puneetsinghania2002/multi-nginx ./nginx
  - docker build -t puneetsinghania2002/multi-server ./server
  - docker build -t puneetsinghania2002/multi-worker ./worker
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push puneetsinghania2002/multi-client
  - docker push puneetsinghania2002/multi-nginx
  - docker push puneetsinghania2002/multi-server
  - docker push puneetsinghania2002/multi-worker

deploy: 
    edge: true
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-ap-south-1-346857477584"
    bucket_path: "multi-docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY